collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6922663
  brandStrength: 0.7163009
  lightness: 0.5537057
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  rhythmicContrast: 0.9194766
typography_spectrum: 0.9361556
layout_spectrum: 1
name: 1_Ted
